# Generated by Django 5.0.6 on 2024-07-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilmReviewApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
